#!/bin/sh
# $Id$

# PROVIDE: mdinit
# BEFORE: FILESYSTEMS
# REQUIRE: mountcritlocal
# KEYWORD: FreeBSD

. /etc/rc.subr

name="mdinit"
start_cmd="mdinit_start"
stop_cmd=":"

PATH=/rescue:/sbin:/bin:
mdinit_start()
{
	if [ -f /.usr.tar.xz ]; then
		mount -t tmpfs tmpfs /usr
		xz -d -c /.usr.tar.xz | tar -x -C / -f -
	elif [ -f /.usr.tar.bz2 ]; then
		mount -t tmpfs tmpfs /usr
		bzip2 -d -c /.usr.tar.bz2 | tar -x -C / -f -
	elif [ -f /.usr.tar.gz ]; then
		mount -t tmpfs tmpfs /usr
		gzip -d -c /.usr.tar.gz | tar -x -C / -f -
	fi
	/sbin/mount -t tmpfs tmpfs /var/db/pkg
	mkdir -p /var/cache/pkg
	/sbin/mount -t tmpfs tmpfs /var/cache/pkg
}

load_rc_config $name
run_rc_command "$1"
